[phases.setup]
nixPkgs = ['nodejs_18', 'yarn-1_x', 'openssl']

[phases.install]
cmds = ['yarn install --frozen-lockfile --network-timeout 100000']

[phases.build]
cmds = ['yarn run build', 'npx prisma db seed']

[start]
cmd = 'yarn run start'
